# Generated by Django 3.2.4 on 2021-06-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210624_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='forme',
            field=models.CharField(choices=[('comprime', 'comprime'), ('sirop', 'sirop'), ('suppo', 'suppo'), ('inj', 'inj')], max_length=15, null=True),
        ),
    ]
